export const Strings = {
  noCustomerData: "No Customers Found",
  interestRate: "Interest Rate",
  amount: "Amount",
  address: "Address",
  mobileNo: "Mobile Number",
  customerName: "Customer Name",
  loading: "Loading...",
  login: "Login",
  email: "Email",
  password: "Password",
  pleaseWait: "Please Wait...",
  noLoanData: "No Loans Found",
  welcomeTo: "Welcome to",
  runDraw: "Run Draw",
  dated: "Dated",
  fetching: "Fetching...",
  noDataFound: "No Data Found",
  totalAmount: "Total Amount",
  loanStatus: "Loan Status",
  selectLoan: "Select Loan",
  submit: "Submit",
  loan: "Loan",
  selectCustomer: "Select Customer",
  select: "Select",
  loanAmount: "Loan Amount",
  createdOn: "Created On",
  amountPaid: "Amount Paid",
  date: "date",
  due: "Due",
  enterValidAmount: "Enter valid amount",
  shouldBeMoreThanZero: "Should be more than 0",
  amountRequired: "Amount is required",
  selectInterestRate: "Select interest rate",
  addNewLoan: "Add New Loan",
  addressRequired: "Address is required",
  mobileNoRequired: "Mobile number is required",
  enterValidMobileNo: "Enter valid mobile number",
  customerNameRequired: "Customer Name is required",
  addCustomer: "Add Customer",
};
